### ISSUE TITLE
the trait  actix_web::[...]::ServiceRequest> is not implemented for actix_web_middleware_redirect_https::RedirectHTTPS

### ISSUE THREAD

**Issue by Codnpix** [petertrotman/actix-web-middleware-redirect-https#5]
Hi,
I'm trying to upgrade from actix-web 3.3.2 to 4.0.1, and an trait implementation issue is showing up
Cargo.toml
```toml
[dependencies]
actix-web = { version="4.0.1", features=["rustls"] }
actix-web-middleware-redirect-https = "3.0.1"
rustls = "0.18.1"
```
main.rs
```rs
use actix_web_middleware_redirect_https::RedirectHTTPS;
// ...
    App::new()
            .wrap(RedirectHTTPS::with_replacements(&[(
                format!(":{}", server_port),
                format!(":{}", server_port_tls),
            )]))
```

Error
```  
the trait bound `actix_web_middleware_redirect_https::RedirectHTTPS: actix_web::dev::Transform<<impl actix_web::dev::ServiceFactory<actix_web::dev::ServiceRequest, Response = actix_web::dev::ServiceResponse<actix_web::middleware::logger::StreamLog<actix_web::body::BoxBody>>, Error = actix_web::Error, Config = (), InitError = ()> as actix_web::dev::ServiceFactory<actix_web::dev::ServiceRequest>>::Service, actix_web::dev::ServiceRequest>` is not satisfied
```

Is there a workaround currently available ?

Thanks for your help.
